/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 25-08-12 9.20 am modified about page
 * 
 */
package Main_package;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nawaf
 */
public class AboutUsUI extends javax.swing.JFrame {


    /**
     * Creates new form AboutUsUI
     */
    public AboutUsUI() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/main_package/resources/icon.png")).getImage());
        setLocationRelativeTo(null);
        weblink.setText("<HTML><FONT color=\"#000099\"><U>http://www.google.com</U></FONT></HTML>");
        contactWebLink.setText("<HTML><FONT color=\"#000099\"><U>http://www.google.com</U></FONT></HTML>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabPane = new javax.swing.JTabbedPane();
        campulseTab = new javax.swing.JPanel();
        campulse = new javax.swing.JLabel();
        campulseIcon = new javax.swing.JLabel();
        campulseDescrition = new javax.swing.JLabel();
        releaseDate = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        prevVersion = new javax.swing.JLabel();
        version2 = new javax.swing.JLabel();
        version1 = new javax.swing.JLabel();
        developers = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        projectLead = new javax.swing.JLabel();
        ganeshAithal = new javax.swing.JLabel();
        aithalDescription = new javax.swing.JLabel();
        projectDesigners = new javax.swing.JLabel();
        matrix = new javax.swing.JPanel();
        weblink = new javax.swing.JLabel();
        softwarepanel = new javax.swing.JPanel();
        name13 = new javax.swing.JLabel();
        name14 = new javax.swing.JLabel();
        name15 = new javax.swing.JLabel();
        name16 = new javax.swing.JLabel();
        designteamPanel = new javax.swing.JPanel();
        name17 = new javax.swing.JLabel();
        name20 = new javax.swing.JLabel();
        name23 = new javax.swing.JLabel();
        name24 = new javax.swing.JLabel();
        name28 = new javax.swing.JLabel();
        name29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        webteampanel = new javax.swing.JPanel();
        name21 = new javax.swing.JLabel();
        name22 = new javax.swing.JLabel();
        contactUstab = new javax.swing.JPanel();
        name9 = new javax.swing.JLabel();
        name10 = new javax.swing.JLabel();
        name11 = new javax.swing.JLabel();
        name12 = new javax.swing.JLabel();
        ganeshAithal1 = new javax.swing.JLabel();
        emailAithal = new javax.swing.JLabel();
        yajneshMail = new javax.swing.JLabel();
        vishalMail = new javax.swing.JLabel();
        jicksonMail = new javax.swing.JLabel();
        nawafMail = new javax.swing.JLabel();
        contactWebLink = new javax.swing.JLabel();
        Thankstab = new javax.swing.JPanel();
        sincereThanx = new javax.swing.JLabel();
        ansariSir = new javax.swing.JLabel();
        arunlabel = new javax.swing.JLabel();
        abuLabel = new javax.swing.JLabel();
        thnxAll = new javax.swing.JLabel();
        ansariSirPost = new javax.swing.JLabel();
        arunPost = new javax.swing.JLabel();
        abuPost = new javax.swing.JLabel();
        hamzaLabel = new javax.swing.JLabel();
        hamzaPost = new javax.swing.JLabel();
        thanxAll1 = new javax.swing.JLabel();
        thanxAll2 = new javax.swing.JLabel();
        matrixInc = new javax.swing.JLabel();
        designedBy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainTabPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        mainTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainTabPane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainTabPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainTabPaneMouseEntered(evt);
            }
        });

        campulseTab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campulseTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campulseTabMouseEntered(evt);
            }
        });

        campulse.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        campulse.setText("Campulse 2.3");

        campulseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/ecg-icon.png"))); // NOI18N

        campulseDescrition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campulseDescrition.setForeground(java.awt.Color.blue);
        campulseDescrition.setText("Short Description");

        releaseDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        releaseDate.setText("Release Date :");

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setText("27-08-2012 ");

        prevVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prevVersion.setText("Previous Versions :");

        version2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        version2.setText("Campulse 1.8");

        version1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        version1.setText("Campulse 1.0");

        javax.swing.GroupLayout campulseTabLayout = new javax.swing.GroupLayout(campulseTab);
        campulseTab.setLayout(campulseTabLayout);
        campulseTabLayout.setHorizontalGroup(
            campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campulseTabLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(campulse)
                .addGap(63, 63, 63))
            .addGroup(campulseTabLayout.createSequentialGroup()
                .addGroup(campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campulseTabLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(campulseIcon))
                    .addGroup(campulseTabLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(releaseDate)
                            .addComponent(prevVersion)
                            .addComponent(campulseDescrition))
                        .addGap(24, 24, 24)
                        .addGroup(campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(version2)
                            .addComponent(date)
                            .addComponent(version1))))
                .addContainerGap())
        );
        campulseTabLayout.setVerticalGroup(
            campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campulseTabLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(campulseIcon)
                .addGap(30, 30, 30)
                .addComponent(campulse)
                .addGap(40, 40, 40)
                .addGroup(campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(releaseDate)
                    .addComponent(date))
                .addGap(18, 18, 18)
                .addGroup(campulseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevVersion)
                    .addComponent(version2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(version1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(campulseDescrition)
                .addGap(44, 44, 44))
        );

        mainTabPane.addTab("Details  ", new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/numbers-icon.png")), campulseTab); // NOI18N

        developers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name1.setText("• Yajnesh Talapadi");

        name2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name2.setText("• Vishal Vijay");

        name3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name3.setText("• Jickson Stephen");

        name4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name4.setText("• Abdul Khader Nawaf");

        projectLead.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        projectLead.setForeground(java.awt.Color.blue);
        projectLead.setText("Project Lead :");

        ganeshAithal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ganeshAithal.setText("Dr.Ganesh Aithal");

        aithalDescription.setText("(HOD. CS Dept. & Vice Principal, PA College, Mangalore)");

        projectDesigners.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        projectDesigners.setForeground(java.awt.Color.blue);
        projectDesigners.setText("Project design  :");

        javax.swing.GroupLayout developersLayout = new javax.swing.GroupLayout(developers);
        developers.setLayout(developersLayout);
        developersLayout.setHorizontalGroup(
            developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(developersLayout.createSequentialGroup()
                .addGroup(developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(developersLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aithalDescription)
                            .addComponent(ganeshAithal)))
                    .addGroup(developersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectLead))
                    .addGroup(developersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(developersLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name3)
                                    .addComponent(name4)
                                    .addComponent(name2)
                                    .addComponent(name1)))
                            .addComponent(projectDesigners))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        developersLayout.setVerticalGroup(
            developersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, developersLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(projectLead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ganeshAithal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aithalDescription)
                .addGap(47, 47, 47)
                .addComponent(projectDesigners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name4)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainTabPane.addTab("  Developers  ", new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/Groups-Meeting-Dark-icon.png")), developers); // NOI18N

        weblink.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weblink.setText("weblink about page");
        weblink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        weblink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weblinkMouseClicked(evt);
            }
        });

        softwarepanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Software Develop Team", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        name13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name13.setText("• Yajnesh Talapadi");

        name14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name14.setText("• Abdul Khader Nawaf");

        name15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name15.setText("• Vishal Vijay");

        name16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name16.setText("• Jickson Stephen");

        javax.swing.GroupLayout softwarepanelLayout = new javax.swing.GroupLayout(softwarepanel);
        softwarepanel.setLayout(softwarepanelLayout);
        softwarepanelLayout.setHorizontalGroup(
            softwarepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softwarepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(softwarepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name15)
                    .addComponent(name14)
                    .addComponent(name16)
                    .addComponent(name13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        softwarepanelLayout.setVerticalGroup(
            softwarepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softwarepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name13)
                .addGap(12, 12, 12)
                .addComponent(name16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        designteamPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creative design Team", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        name17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name17.setText("• Jijith");

        name20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name20.setText("• Devi Prasath");

        name23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name23.setText("• Ashwin Valento");

        name24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name24.setText("• Aravind Venugopal");

        name28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name28.setText("• Mithesh Suvarna");

        name29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name29.setText("• Arshad Mohammed");

        jLabel2.setText("• Sahana DN");

        javax.swing.GroupLayout designteamPanelLayout = new javax.swing.GroupLayout(designteamPanel);
        designteamPanel.setLayout(designteamPanelLayout);
        designteamPanelLayout.setHorizontalGroup(
            designteamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designteamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(designteamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(designteamPanelLayout.createSequentialGroup()
                        .addGroup(designteamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(designteamPanelLayout.createSequentialGroup()
                                .addComponent(name20, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(designteamPanelLayout.createSequentialGroup()
                                .addComponent(name17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(78, 78, 78))
                            .addGroup(designteamPanelLayout.createSequentialGroup()
                                .addComponent(name23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addComponent(name28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(designteamPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50)))
                        .addGap(12, 12, 12))
                    .addGroup(designteamPanelLayout.createSequentialGroup()
                        .addComponent(name29)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designteamPanelLayout.createSequentialGroup()
                        .addComponent(name24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        designteamPanelLayout.setVerticalGroup(
            designteamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designteamPanelLayout.createSequentialGroup()
                .addComponent(name17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name28)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        webteampanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Web Develop Team", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        name21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name21.setText("• Ajay Kumar");

        name22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name22.setText("• Sanoob Siddiq");

        javax.swing.GroupLayout webteampanelLayout = new javax.swing.GroupLayout(webteampanel);
        webteampanel.setLayout(webteampanelLayout);
        webteampanelLayout.setHorizontalGroup(
            webteampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webteampanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webteampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name22)
                    .addComponent(name21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        webteampanelLayout.setVerticalGroup(
            webteampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webteampanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name21)
                .addGap(12, 12, 12)
                .addComponent(name22)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout matrixLayout = new javax.swing.GroupLayout(matrix);
        matrix.setLayout(matrixLayout);
        matrixLayout.setHorizontalGroup(
            matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matrixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(matrixLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(softwarepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webteampanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(designteamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(matrixLayout.createSequentialGroup()
                        .addComponent(weblink)
                        .addContainerGap())))
        );
        matrixLayout.setVerticalGroup(
            matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matrixLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(matrixLayout.createSequentialGroup()
                        .addComponent(softwarepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(webteampanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(weblink))
                    .addComponent(designteamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Matrix Inc.  ", new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/Matrix-icon.png")), matrix); // NOI18N

        name9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name9.setText("• Yajnesh Talapadi");

        name10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name10.setText("• Vishal Vijay");

        name11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name11.setText("• Jickson Stephen");

        name12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name12.setText("• Abdul Khader Nawaf");

        ganeshAithal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ganeshAithal1.setText("• Dr.Ganesh Aithal");

        emailAithal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailAithal.setForeground(java.awt.Color.blue);
        emailAithal.setText("ganesh.aithal@gmail.com");

        yajneshMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yajneshMail.setForeground(java.awt.Color.blue);
        yajneshMail.setText("yajnesh.talapady@gmail.com");

        vishalMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vishalMail.setForeground(java.awt.Color.blue);
        vishalMail.setText("vishal.vijay@gmail.com");

        jicksonMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jicksonMail.setForeground(java.awt.Color.blue);
        jicksonMail.setText("jickson.stephen@yahoo.com");

        nawafMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nawafMail.setForeground(java.awt.Color.blue);
        nawafMail.setText("nawaf331@gmail.com");

        contactWebLink.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactWebLink.setText("Web linkt to contactUs Page");
        contactWebLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactWebLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactWebLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contactUstabLayout = new javax.swing.GroupLayout(contactUstab);
        contactUstab.setLayout(contactUstabLayout);
        contactUstabLayout.setHorizontalGroup(
            contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactUstabLayout.createSequentialGroup()
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactUstabLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactUstabLayout.createSequentialGroup()
                                .addComponent(name11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jicksonMail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(contactUstabLayout.createSequentialGroup()
                                    .addComponent(ganeshAithal1)
                                    .addGap(40, 40, 40)
                                    .addComponent(emailAithal))
                                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactUstabLayout.createSequentialGroup()
                                        .addComponent(name9)
                                        .addGap(39, 39, 39)
                                        .addComponent(yajneshMail))
                                    .addGroup(contactUstabLayout.createSequentialGroup()
                                        .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(name12)
                                            .addComponent(name10))
                                        .addGap(18, 18, 18)
                                        .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vishalMail)
                                            .addComponent(nawafMail)))))))
                    .addGroup(contactUstabLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(contactWebLink)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contactUstabLayout.setVerticalGroup(
            contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactUstabLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ganeshAithal1)
                    .addComponent(emailAithal))
                .addGap(27, 27, 27)
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name9)
                    .addComponent(yajneshMail))
                .addGap(28, 28, 28)
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name12)
                    .addComponent(nawafMail))
                .addGap(28, 28, 28)
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name10)
                    .addComponent(vishalMail))
                .addGap(32, 32, 32)
                .addGroup(contactUstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name11)
                    .addComponent(jicksonMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(contactWebLink)
                .addGap(44, 44, 44))
        );

        mainTabPane.addTab("Contact Us  ", new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/phone-icon.png")), contactUstab); // NOI18N

        sincereThanx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sincereThanx.setForeground(java.awt.Color.blue);
        sincereThanx.setText("Our Sincere Thanks to :");

        ansariSir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansariSir.setText("Ansari sir");

        arunlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arunlabel.setText("Arun Sir");

        abuLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abuLabel.setText("Abu");

        thnxAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thnxAll.setText("and All Lecturers, Students 2009-2010 batch of");

        ansariSirPost.setText("--    Senior Lecturer, CS Dept. PA college");

        arunPost.setText("--    Lab Assistant, CS Dept. PA college");

        abuPost.setText("--    Lab Assistant, CS Dept. PA college");

        hamzaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hamzaLabel.setText("Hamza");

        hamzaPost.setText("--   Some Post. PA college");

        thanxAll1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thanxAll1.setText("PA College of Engineering who co-ordinated");

        thanxAll2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thanxAll2.setText("and Co-operated with us ");

        javax.swing.GroupLayout ThankstabLayout = new javax.swing.GroupLayout(Thankstab);
        Thankstab.setLayout(ThankstabLayout);
        ThankstabLayout.setHorizontalGroup(
            ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThankstabLayout.createSequentialGroup()
                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThankstabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sincereThanx))
                    .addGroup(ThankstabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThankstabLayout.createSequentialGroup()
                                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ansariSir)
                                    .addComponent(abuLabel)
                                    .addComponent(arunlabel)
                                    .addComponent(hamzaLabel))
                                .addGap(42, 42, 42)
                                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hamzaPost)
                                    .addComponent(arunPost)
                                    .addComponent(abuPost)
                                    .addComponent(ansariSirPost)))
                            .addComponent(thnxAll)
                            .addGroup(ThankstabLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(thanxAll1))))
                    .addGroup(ThankstabLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(thanxAll2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ThankstabLayout.setVerticalGroup(
            ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThankstabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(sincereThanx)
                .addGap(30, 30, 30)
                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansariSir)
                    .addComponent(ansariSirPost))
                .addGap(18, 18, 18)
                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arunlabel)
                    .addComponent(arunPost))
                .addGap(18, 18, 18)
                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abuLabel)
                    .addComponent(abuPost))
                .addGap(18, 18, 18)
                .addGroup(ThankstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamzaLabel)
                    .addComponent(hamzaPost))
                .addGap(29, 29, 29)
                .addComponent(thnxAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thanxAll1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thanxAll2)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mainTabPane.addTab("  Thanks To  ", new javax.swing.ImageIcon(getClass().getResource("/Main_package/resources/hand-icon.png")), Thankstab); // NOI18N

        matrixInc.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        matrixInc.setForeground(new java.awt.Color(0, 153, 51));
        matrixInc.setText("Matrix Inc.");

        designedBy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designedBy.setText("Designed And Developed By :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(designedBy)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(matrixInc)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(designedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matrixInc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainTabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainTabPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabPaneMouseEntered
        
    }//GEN-LAST:event_mainTabPaneMouseEntered

    private void campulseTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campulseTabMouseEntered
       
    }//GEN-LAST:event_campulseTabMouseEntered

    private void weblinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weblinkMouseClicked
        Desktop desktop = Desktop.getDesktop();
            try {
                URI uri = new URI("http://www.google.com");
                desktop.browse(uri);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error in opening browser. please check your internet connection", "error", JOptionPane.ERROR_MESSAGE);
                
            }

    }//GEN-LAST:event_weblinkMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Run.Runner.RunnerObj.MainUIObj.show();
    }//GEN-LAST:event_formWindowClosing

    private void contactWebLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactWebLinkMouseClicked
        Desktop desktop = Desktop.getDesktop();
            try {
                URI uri = new URI("http://www.google.com");
                desktop.browse(uri);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error in opening browser. please check your internet connection", "error", JOptionPane.ERROR_MESSAGE);
                
            }
    }//GEN-LAST:event_contactWebLinkMouseClicked

    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Thankstab;
    private javax.swing.JLabel abuLabel;
    private javax.swing.JLabel abuPost;
    private javax.swing.JLabel aithalDescription;
    private javax.swing.JLabel ansariSir;
    private javax.swing.JLabel ansariSirPost;
    private javax.swing.JLabel arunPost;
    private javax.swing.JLabel arunlabel;
    private javax.swing.JLabel campulse;
    private javax.swing.JLabel campulseDescrition;
    private javax.swing.JLabel campulseIcon;
    private javax.swing.JPanel campulseTab;
    private javax.swing.JPanel contactUstab;
    private javax.swing.JLabel contactWebLink;
    private javax.swing.JLabel date;
    private javax.swing.JLabel designedBy;
    private javax.swing.JPanel designteamPanel;
    private javax.swing.JPanel developers;
    private javax.swing.JLabel emailAithal;
    private javax.swing.JLabel ganeshAithal;
    private javax.swing.JLabel ganeshAithal1;
    private javax.swing.JLabel hamzaLabel;
    private javax.swing.JLabel hamzaPost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jicksonMail;
    private javax.swing.JTabbedPane mainTabPane;
    private javax.swing.JPanel matrix;
    private javax.swing.JLabel matrixInc;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name10;
    private javax.swing.JLabel name11;
    private javax.swing.JLabel name12;
    private javax.swing.JLabel name13;
    private javax.swing.JLabel name14;
    private javax.swing.JLabel name15;
    private javax.swing.JLabel name16;
    private javax.swing.JLabel name17;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name20;
    private javax.swing.JLabel name21;
    private javax.swing.JLabel name22;
    private javax.swing.JLabel name23;
    private javax.swing.JLabel name24;
    private javax.swing.JLabel name28;
    private javax.swing.JLabel name29;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name9;
    private javax.swing.JLabel nawafMail;
    private javax.swing.JLabel prevVersion;
    private javax.swing.JLabel projectDesigners;
    private javax.swing.JLabel projectLead;
    private javax.swing.JLabel releaseDate;
    private javax.swing.JLabel sincereThanx;
    private javax.swing.JPanel softwarepanel;
    private javax.swing.JLabel thanxAll1;
    private javax.swing.JLabel thanxAll2;
    private javax.swing.JLabel thnxAll;
    private javax.swing.JLabel version1;
    private javax.swing.JLabel version2;
    private javax.swing.JLabel vishalMail;
    private javax.swing.JLabel weblink;
    private javax.swing.JPanel webteampanel;
    private javax.swing.JLabel yajneshMail;
    // End of variables declaration//GEN-END:variables
}
